### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by evsheffield** [jtrussell/jquery.spindle#2]
;)

**Comment by jtrussell** [comment]
I would love a PR (css solution preferred).

Added literally every combination of vendor prefixes and even added a 50% keyframe just in case FF was being smart about the start and end points being the same.

**Comment by evsheffield** [comment]
It seems like Firefox needs the rotated element to be block level or inline block. See the definition of "transformable" [here](https://drafts.csswg.org/css-transforms-1/#terminology). Perhaps the other browsers are more okay transforming inline elements (?)

Adding `display: inline-block` to the span seems to fix it. http://jsbin.com/lidewu/edit?html,css,output

Does that seem like a reasonable solution? If so I'll submit a PR.

**Comment by jtrussell** [comment]
Sweet. I'd say making the `.spindle-wrapper .spindle.spindle-active` element should be fine. It's wrapper or containing element can still be block level so I don't think we're killing anyone's dreams ;). PR away!

**Comment by jtrussell** [comment]
Thanks @evsheffield!
